### ISSUE TITLE
dist_react typo?

### ISSUE THREAD

**Issue by no-stack-dub-sack** [axilis/typescript-fullstack#4]
Is [this](https://github.com/axilis/typescript-fullstack/blob/4db486f6eb99e8d49f2a9025863a1f90b649b4da/react/config/tsconfig.json#L3) a typo? 

```json
    "outDir": "dist_react", 
```

It looks like its referred to as `dist-react` everywhere else. 

Great project by the way! This has really helped me nail down a folder structure and scripts for my fullstack typescript project.

**Comment by Soudny** [comment]
Good catch! Thanks! I'll update it shortly

**Comment by no-stack-dub-sack** [comment]
@Soudny :+1:
