### ISSUE TITLE
where is the typescript?

### ISSUE THREAD

**Issue by nshCore** [axilis/typescript-fullstack#5]
It says you have used typescript but it is just plain javascript with a .ts extension?

**Comment by Soudny** [comment]
I assure you that what's being used is typescript. Most notable changes can be seen in React part of the boilerplate where the syntax is slightly different than plain-javascript one.

I encourage you to familiarize yourself with TS and have another look. The most important thing I would stress out is that valid javascript code is also valid TS code, but not the other way around.
